[package]
name = "rocoder"
version = "0.1.0"
authors = ["Andrew Yoon <andrew@nothing-to-say.org>"]
edition = "2018"

[lib]
name = "rocoder"
path = "src/lib.rs"

[[bin]]
name = "rocoder"
path = "src/main.rs"

[[bin]]
name = "play"
path = "src/play_bin.rs"

[[bin]]
name = "cl_sandbox"
path = "src/cl_sandbox.rs"

[dependencies]
rustfft = "*"
num-traits = "*"
hound = "*"
rand = "0.7"
stopwatch = "0.0.7"
log = "*"
simplelog = "*"
chrono = "*"
futures = "*"  # needed just for join_all - could reimplement to lower compile time
structopt = "*"
async-std = "*"
minimp3 = "*"
cpal = "*"
libc = "*"
custom_error = "*"
pbr = "*"
ctrlc = "*"
ocl = "*"
anyhow = "1.0"

[dev-dependencies]
test-case = "0.3.3"
