[package]
name = "rocoder"
version = "0.1.0"
authors = ["Andrew Yoon <andrew@nothing-to-say.org>"]
edition = "2018"

[lib]
name = "rocoder"
path = "src/lib.rs"

[[bin]]
name = "rocoder"
path = "src/main.rs"

[[bin]]
name = "play"
path = "src/play_bin.rs"

[[bin]]
name = "installation"
path = "src/installation.rs"

[profile.release]
debug = true  # keep debug symbols in release build for profiling

[dependencies]
rustfft = "*"
num-traits = "*"
hound = "*"
rand = "0.7"
stopwatch = "0.0.7"
log = "*"
simplelog = "*"
structopt = "*"
minimp3 = "*"
cpal = "0.11"
libc = "*"
pbr = "*"
ctrlc = "*"
anyhow = "1.0"
libloading = "0.5"
tempfile = "*"
crossbeam-channel = "*"
fwatch = "0.1.5"
slice-deque = "*"
slice_ring_buf = "0.2"

[dev-dependencies]
test-case = "0.3.3"
